### ISSUE TITLE
"Inspect UI5 control" in Crome context menu doesn't work

### ISSUE THREAD

**Issue by skamok** [SAP/ui5-inspector#184]
It's issue present in 1.0.1 version.

**Comment by dobrinyonkov** [comment]
Hi @skamok, 

this was fixed with #186 but is not yet released to the chrome web store. 
If you would like to consume the fix now you can follow the steps here to download and use the latest version released to github: https://github.com/SAP/ui5-inspector#direct-download-and-use 

Thanks and Best Regards,
Dobrin

**Comment by skamok** [comment]
> Hi @skamok,
> 
> this was fixed with #186 but is not yet released to the chrome web store. If you would like to consume the fix now you can follow the steps here to download and use the latest version released to github: https://github.com/SAP/ui5-inspector#direct-download-and-use
> 
> Thanks and Best Regards, Dobrin

Hi thank you, now context menu works fine. But you forget to change version to 1.2.0 in Manifest or may be version will be updated when it placed in Crome Store
