### ISSUE TITLE
BaseConfig (sap/base/config/_Configuration) error

### ISSUE THREAD

**Issue by AlexNecula-Cashtriba** [SAP/ui5-inspector#255]
Hi,

I am suddenly (not sure what triggered it) experiencing an error with the extension. The tab is still available in the console log, however it is empty.

The cause is the below function which tries to retrieve the debug info using BaseConfig.

![image](https://github.com/SAP/ui5-inspector/assets/80784326/c0f1e34a-d63d-4d73-aadd-9ac7fa54c23a)

BaseConfig is retrieved at the beginning of ToolsAPI.js as below:
`var BaseConfig = sap.ui.require('sap/base/config/_Configuration');`

Unfortunately, this fails therefore the error is triggered. If I make via debugging a dummy BaseConfig object with a method "get" that just returns "true", the extension seems to work alright, so at least I have a workaround for now.

SAPUI5 version: 1.96.12

Thank you,
Alex

**Comment by yanaminkova** [comment]
Hello @AlexNecula-Cashtriba,

This issue is duplicate to https://github.com/SAP/ui5-inspector/issues/250, which was fixed with https://github.com/SAP/ui5-inspector/pull/251 and will be part of the new relеase.
Meanwhile, if necessary you could use the older version (1.6.1).
You can find the steps on the following link under "Direct download and use": https://github.com/SAP/ui5-inspector#direct-download-and-use

Thanks and Best regards,
Yana
