### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by sgarland** [SAP/ui5-inspector#92]
When inspecting UI controls with bindings to an instance of `sap.ui.model.base.ManagedObjectModel` I see this kind of error:

```
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'fnClass'
    |     property 'mAggregations' -> object with constructor 'Object'
    |     property 'items' -> object with constructor 'Array'
    |     ...
    |     index 0 -> object with constructor 'Object'
    --- property 'oListener' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.send (main.js:849)
    at Object.do-control-select (main.js:108)
    at HTMLDocument.communicationWithContentScript (main.js:180)
```

In this case the model data is a UI5 control. The object graph for a UI5 control can contain cycles because of event listener object references, so a UI5 control cannot be serialised by using JSON.stringify() in an unmodified form.

**Comment by LukasHeimann** [comment]
The issue seems to come from https://github.com/SAP/ui5-inspector/blob/master/app/scripts/modules/injected/message.js#L10. I'm not completely sure, why the way through `JSON.parse(JSON.stringify(...))` was introduced.

- To deeply copy the object? In this case we should use something like https://github.com/juanluispaz/clone-deep-circular-references
- To remove non-data properties (https://github.com/SAP/ui5-inspector/pull/74/files)? Then a more robust alternative should be introduced...
